"""add recipe sharing columns

Revision ID: db436a86ad91
Revises: 006
Create Date: 2026-01-08 08:46:12.730846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db436a86ad91'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_categories_user_name'), 'categories', type_='unique')
    op.alter_column('meal_plan_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_meal_plan_items_plan_id'), table_name='meal_plan_items')
    op.create_index(op.f('ix_meal_plan_items_meal_plan_id'), 'meal_plan_items', ['meal_plan_id'], unique=False)
    op.alter_column('meal_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('meal_plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_meal_plans_user_week'), table_name='meal_plans')
    op.drop_constraint(op.f('uq_meal_plans_user_week'), 'meal_plans', type_='unique')
    op.create_index(op.f('ix_meal_plans_user_id'), 'meal_plans', ['user_id'], unique=False)
    op.drop_index(op.f('ix_recipe_categories_category_id'), table_name='recipe_categories')
    op.add_column('recipes', sa.Column('share_token', sa.String(length=32), nullable=True))
    op.add_column('recipes', sa.Column('is_shared', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('recipes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('recipes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_recipes_favorite'), table_name='recipes', postgresql_where='(is_favorite = true)')
    op.create_index(op.f('ix_recipes_share_token'), 'recipes', ['share_token'], unique=True)
    op.alter_column('shopping_list_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_shopping_list_items_list_id'), table_name='shopping_list_items')
    op.create_index(op.f('ix_shopping_list_items_shopping_list_id'), 'shopping_list_items', ['shopping_list_id'], unique=False)
    op.alter_column('shopping_lists', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shopping_lists', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(length=2),
               nullable=False,
               existing_server_default=sa.text("'en'::character varying"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(length=2),
               nullable=True,
               existing_server_default=sa.text("'en'::character varying"))
    op.alter_column('shopping_lists', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('shopping_lists', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_shopping_list_items_shopping_list_id'), table_name='shopping_list_items')
    op.create_index(op.f('ix_shopping_list_items_list_id'), 'shopping_list_items', ['shopping_list_id'], unique=False)
    op.alter_column('shopping_list_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_recipes_share_token'), table_name='recipes')
    op.create_index(op.f('ix_recipes_favorite'), 'recipes', ['user_id', 'is_favorite'], unique=False, postgresql_where='(is_favorite = true)')
    op.alter_column('recipes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('recipes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('recipes', 'is_shared')
    op.drop_column('recipes', 'share_token')
    op.create_index(op.f('ix_recipe_categories_category_id'), 'recipe_categories', ['category_id'], unique=False)
    op.drop_index(op.f('ix_meal_plans_user_id'), table_name='meal_plans')
    op.create_unique_constraint(op.f('uq_meal_plans_user_week'), 'meal_plans', ['user_id', 'week_start'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_meal_plans_user_week'), 'meal_plans', ['user_id', 'week_start'], unique=False)
    op.alter_column('meal_plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('meal_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_meal_plan_items_meal_plan_id'), table_name='meal_plan_items')
    op.create_index(op.f('ix_meal_plan_items_plan_id'), 'meal_plan_items', ['meal_plan_id'], unique=False)
    op.alter_column('meal_plan_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(op.f('uq_categories_user_name'), 'categories', ['user_id', 'name'], postgresql_nulls_not_distinct=False)
    op.alter_column('categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
